<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>NSPdfMerge</AssemblyName>
    <ApplicationIcon>..\..\flux-dev_A_futuristic_icon_for_a_program_that_combines_PDF_files_into_one_the_program_is_-1.ico</ApplicationIcon>
    <Win32Icon>..\..\flux-dev_A_futuristic_icon_for_a_program_that_combines_PDF_files_into_one_the_program_is_-1.ico</Win32Icon>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>1.2.0</Version>
    <AssemblyVersion>1.2.0.0</AssemblyVersion>
    <FileVersion>1.2.0.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MaterialDesignThemes" Version="4.9.0" />
    <PackageReference Include="MaterialDesignColors" Version="2.1.4" />
    <PackageReference Include="PdfSharp" Version="6.1.1" />
    <PackageReference Include="ExcelDataReader" Version="3.7.0" />
    <PackageReference Include="ExcelDataReader.DataSet" Version="3.7.0" />
  </ItemGroup>

</Project>
